name: PR Checks

on:
  pull_request:
    branches: [ main, develop ]

  workflow_dispatch:

jobs:
  python-sql-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          
      - name: Install dependencies
        run: poetry install
        
      - name: Run all checks
        run: |
          make lint
          make format
          make sql-lint


  terraform-check:
    runs-on: ubuntu-latest
    needs: python-check
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      
      - name: Run Terraform Checks
        id: plan
        run: |
          cd terraform
          terraform init -backend=false
          terraform fmt -check -recursive
          terraform validate
